.Dd January 19, 2013
.Dt ewfexport
.Os libewf
.Sh NAME
.Nm ewfexport
.Nd exports media data stored in EWF files
.Sh SYNOPSIS
.Nm ewfexport
.Op Fl A Ar codepage
.Op Fl b Ar number_of_sectors
.Op Fl B Ar number_of_bytes
.Op Fl c Ar compression_values
.Op Fl d Ar digest_type
.Op Fl f Ar format
.Op Fl l Ar log_filename
.Op Fl o Ar offset
.Op Fl p Ar process_buffer_size
.Op Fl S Ar segment_file_size
.Op Fl t Ar target
.Op Fl hqsuvVw
.Ar ewf_files
.Sh DESCRIPTION
.Nm ewfexport
is a utility to export media data stored in EWF files.
.Pp
.Nm ewfexport
is part of the
.Nm libewf
package.
.Nm libewf
is a library to support the Expert Witness Compression Format (EWF).
.Pp
.Ar ewf_files
the first or the entire set of EWF segment files
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar codepage
the codepage of header section, options: ascii (default), windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl b Ar number_of_sectors
the number of sectors to read at once (per chunk), options: 16, 32, 64 (default), 128, 256, 512, 1024, 2048, 4096, 8192, 16384 or 32768
.It Fl B Ar number_of_bytes
the number of bytes to export
.It Fl c Ar compression_values
specify the compression values as: level or method:level
compression method options: deflate (default), bzip2 (bzip2 is only supported by EWF2 formats)
compression level options: none (default), empty-block, fast or best
.It Fl d Ar digest_type
calculate additional digest (hash) types besides md5, options: sha1 (not used for raw and files formats)
.It Fl f Ar format
the output format to write to, options: raw (default), files (restricted to logical volume files), ewf, smart, ftk, encase1, encase2, encase3, encase4, encase5, encase6, encase7, encase7-v2, linen5, linen6, linen7, ewfx.
.It Fl h
shows this help
.It Fl l Ar log_filename
logs export errors and the digest (hash) to the log filename
.It Fl o Ar offset
the offset to start the export (default is 0)
.It Fl p Ar process_buffer_size
the process buffer size (default is the chunk size)
.It Fl s
swap byte pairs of the media data (from AB to BA) (use this for big to little endian conversion and vice versa)
.It Fl S Ar segment_file_size
the segment file size in bytes (default is 1.4 GiB) (minimum is 1.0 MiB, maximum is 7.9 EiB for raw, encase6 and encase7 format and 1.9 GiB for other formats) (not used for files format)
.It Fl t Ar target
the target file to export to, use \- for stdout (default is export) stdout is only supported for the raw format
.It Fl u
unattended mode (disables user interaction)
.It Fl v
verbose output to stderr
.It Fl V
print version
.It Fl w
zero sectors on checksum error (mimic EnCase like behavior)
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Nm ewfexport
will ask the information it needs.
.Bd -literal
# ewfexport floppy.E01
ewfexport 20120805

Information for export required, please provide the necessary input
Export to format (raw, files, ewf, smart, ftk, encase1, encase2, encase3, encase4, encase5, encase6, encase7, encase7-v2, linen5, linen6, linen7, ewfx) [raw]:
Target path and filename without extension or \- for stdout: floppy
Evidence segment file size in bytes (1.0 MiB <= value <= 7.9 EiB) [1.4 GiB]:
Start export at offset (0 <= value <= 1474560) [0]:
Number of bytes to export (0 <= value <= 1474560) [1474560]:

Export started at: Sun Aug  5 19:19:40 2012

This could take a while.

Status: at 2%.
        exported 32 kB (32768 bytes) of total 1.4 MiB (1474560 bytes).

.Dl ...

Status: at 100%.
        exported 1.4 MiB (1474560 bytes) of total 1.4 MiB (1474560 bytes).
        completion in 1 second(s) with 1 MiB/s (1474560 bytes/second).

Export completed at: Sun Aug  5 19:19:41 2012

Written: 1.4 MiB (1474560 bytes) in 1 second(s) with 1 MiB/s (1474560 bytes/second).
MD5 hash calculated over data:		ae1ce8f5ac079d3ee93f97fe3792bda3
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled. Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/libewf/
.Sh AUTHOR
.Pp
These man pages were written by Kees Mastwijk.
.Pp
Alterations for distribution have been made by Joachim Metz.
.Sh COPYRIGHT
.Pp
Copyright 2006-2013 Joachim Metz <joachim.metz@gmail.com>.
.Pp
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr ewfacquire 1 ,
.Xr ewfacquirestream 1 ,
.Xr ewfinfo 1 ,
.Xr ewfmount 1 ,
.Xr ewfrecover 1 ,
.Xr ewfverify 1
