.Dd January 19, 2013
.Dt ewfinfo
.Os libewf
.Sh NAME
.Nm ewfinfo
.Nd show meta data stored in EWF files
.Sh SYNOPSIS
.Nm ewfinfo
.Op Fl A Ar codepage
.Op Fl d Ar date_format
.Op Fl f Ar format
.Op Fl ehimvV
.Ar ewf_files
.Sh DESCRIPTION
.Nm ewfinfo
is a utility to show meta data stored in EWF files.
.Pp
.Nm ewfinfo
is part of the
.Nm libewf
package.
.Nm libewf
is a library to support the Expert Witness Compression Format (EWF).
.Pp
.Ar ewf_files
the first or the entire set of EWF segment files
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar codepage
the codepage of header section, options: ascii (default), windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl d Ar date_format
the date format, options: ctime (default), dm (day/month), md (month/day), iso8601
.It Fl e
only show EWF read error information
.It Fl f Ar format
specify the output format, options: text (default), dfxml
.It Fl h
shows this help
.It Fl i
only show EWF acquiry information
.It Fl m
only show EWF media information
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# ewfinfo \-d dm floppy.E01
ewfinfo 20120805

Acquiry information
        Case number:            1
        Description:            Floppy
        Examiner name:          John D.
        Evidence number:        1.1
        Notes:                  Just a floppy in my system
        Acquiry date:           09/12/2006 10:00:12
        System date:            09/12/2006 10:00:12
        Operating system used:  Linux
        Software version used:  20061209
        Password:               N/A

EWF information
	File format:		EnCase 5
	Sectors per chunk:	64
	Error granularity:	64
	Compression method:	deflate
	Compression level:	no compression
	Set identifier:		869910fc-e143-4908-9328-afedf4a7be1e

Media information
        Media type:             removable disk
        Is physical:		no
        Bytes per sector:       512
        Number of sectors:      2880
        Media size:             1.4 MiB (1474560 bytes)

Digest hash information
        MD5:                    ae1ce8f5ac079d3ee93f97fe3792bda3

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled. Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/libewf/
.Sh AUTHOR
.Pp
These man pages were written by Kees Mastwijk.
.Pp
Alterations for distribution have been made by Joachim Metz.
.Sh COPYRIGHT
.Pp
Copyright 2006-2013 Joachim Metz <joachim.metz@gmail.com>.
.Pp
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr ewfacquire 1 ,
.Xr ewfacquirestream 1 ,
.Xr ewfexport 1 ,
.Xr ewfmount 1 ,
.Xr ewfrecover 1 ,
.Xr ewfverify 1
