.Dd January 19, 2013
.Dt ewfmount
.Os libewf
.Sh NAME
.Nm ewfmount
.Nd mount data stored in EWF files
.Sh SYNOPSIS
.Nm ewfmount
.Op Fl f Ar format
.Op Fl X Ar extended_options
.Op Fl hvV
.Ar ewf_files
.Sh DESCRIPTION
.Nm ewfmount
is a utility to mount data stored in EWF files.
.Pp
.Nm ewfmount
is part of the
.Nm libewf
package.
.Nm libewf
is a library to support the Expert Witness Compression Format (EWF).
.Pp
.Ar ewf_files
the first or the entire set of EWF segment files
.Ar mount_point
the directory to serve as mount point
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar format
specify the input format, options: raw (default), files (restricted to logical volume files)
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.It Fl X Ar extended_options
extended options to pass to sub system
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# ewfmount floppy.E01 floppy/
ewfmount 20110918


.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled. Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/libewf/
.Sh AUTHOR
.Pp
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
.Pp
Copyright 2006-2013 Joachim Metz <joachim.metz@gmail.com>.
.Pp
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr ewfacquire 1 ,
.Xr ewfacquirestream 1 ,
.Xr ewfexport 1 ,
.Xr ewfinfo 1 ,
.Xr ewfrecover 1 ,
.Xr ewfverify 1
