.Dd June 27, 2026
.Dt EWFVERIFY 1
.Os
.Sh NAME
.Nm ewfverify
.Nd verifies media data stored in an Expert Witness Compression Format (EWF) \
image
.Sh SYNOPSIS
.Nm ewfverify
.Op Fl A Ar codepage
.Op Fl d Ar digest_type
.Op Fl f Ar format
.Op Fl j Ar jobs
.Op Fl l Ar log_file
.Op Fl p Ar buffer_size
.Op Fl hqvVwx
.Ar sources
.Sh DESCRIPTION
.Nm ewfverify
is a utility to verify media data stored in an Expert Witness Compression \
Format (EWF) image
.Pp
.Nm ewfverify
is part of the
.Nm libewf
package.
.Nm libewf
is a library to access the Expert Witness Compression Format (EWF)
.Pp
.Ar sources
first or all files of a set of EWF segment files
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar codepage
the codepage of header section, options: ascii (default), windows-874, \
windows-932, windows-936, windows-949, windows-950, windows-1250, \
windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, \
windows-1256, windows-1257 or windows-1258
.It Fl d Ar digest_type
calculate digest (hash) types, options: md5, sha1, sha256.
By default ewfverify will calculate the digest (hash) types that are stored in \
the EWF segment files or MD5 if none.
.It Fl f Ar format
specify the input format, options: raw (default), files (restricted to logical \
volume files)
.It Fl j Ar jobs
the number of concurrent processing jobs (threads), where a number of 0 \
represents single-threaded mode (default is 4 if multi-threaded mode is \
supported).
.It Fl h
shows this help
.It Fl l Ar log_file
logs verification errors and the digest (hash) to a file
.It Fl p Ar buffer_size
specify the process buffer size (default is the 32768)
.It Fl q
quiet shows minimal status information
.It Fl v
verbose output to stderr
.It Fl V
print version
.It Fl w
zero sectors on checksum error (mimic EnCase like behavior)
.It Fl x
use the data chunk functions instead of the buffered read and write functions
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Nm ewfverify
can either verify the raw storage media data or logical file data stored in \
EWF file(s).
.Ss To verify the raw storage media data
.Bd -literal
# ewfverify -q floppy.E01
ewfverify 20260627
.sp
MD5 hash stored in file:		ae1ce8f5ac079d3ee93f97fe3792bda3
MD5 hash calculated over data:		ae1ce8f5ac079d3ee93f97fe3792bda3
.sp
ewfverify: SUCCESS
.Ed
.Ss To verify logical file data
.Bd -literal
# ewfverify -f files -q logical.E01
ewfverify 20260627
.sp
Single file: file1.txt
MD5 hash stored in file:		6fef2a64afbf070a264366183698bb5e
MD5 hash calculated over data:		6fef2a64afbf070a264366183698bb5e
.sp
ewfverify: SUCCESS
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr ewfacquire 1 ,
.Xr ewfacquirestream 1 ,
.Xr ewfexport 1 ,
.Xr ewfinfo 1 ,
.Xr ewfmount 1 ,
.Xr ewfrecover 1
.Sh AUTHORS
.An Kees Mastwijk ,
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libewf/issues
.Sh COPYRIGHT
Copyright (C) 2006-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
