Document: libewf
Title: Debian libewf Manual
Author: <insert document author here>
Abstract: This manual describes what libewf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libewf/libewf.sgml.gz

Format: postscript
Files: /usr/share/doc/libewf/libewf.ps.gz

Format: text
Files: /usr/share/doc/libewf/libewf.text.gz

Format: HTML
Index: /usr/share/doc/libewf/html/index.html
Files: /usr/share/doc/libewf/html/*.html

  
