/* libewf/libewf_config.h.  Generated by configure.  */
/* libewf/libewf_config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `atol' function. */
#define HAVE_ATOL 1

/* Define to 1 if you have the `btowc' function. */
/* #undef HAVE_BTOWC */

/* Defines if buffer passthrough should be used */
/* #undef HAVE_BUFFER_PASSTHROUGH */

/* Defines if chunk cache passthrough should be used */
/* #undef HAVE_CHUNK_CACHE_PASSTHROUGH */

/* Defines if compressBound funtion is present in zlib. */
#define HAVE_COMPRESS_BOUND 1

/* Define to 1 if you have the `ctime' function. */
#define HAVE_CTIME 1

/* Define to 1 if you have the ctime_r function. */
#define HAVE_CTIME_R 1

/* Define to 1 if you have the ctime_r function with a third size argument. */
/* #undef HAVE_CTIME_R_SIZE */

/* Define to 1 if you have the <cygwin/fs.h> header file. */
/* #undef HAVE_CYGWIN_FS_H */

/* Defines if debug output should be used */
/* #undef HAVE_DEBUG_OUTPUT */

/* Define to 1 if you have the declaration of `memrchr ', and to 0 if you
   don't. */
#define HAVE_DECL_MEMRCHR_ 0

/* Define to 1 if you have the declaration of `strerror_r', and to 0 if you
   don't. */
#define HAVE_DECL_STRERROR_R 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fgets' function. */
#define HAVE_FGETS 1

/* Define to 1 if you have the `fgetws' function. */
/* #undef HAVE_FGETWS */

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <glob.h> header file. */
#define HAVE_GLOB_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the `uuid' library (-luuid). */
#define HAVE_LIBUUID 1

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <linux/fs.h> header file. */
#define HAVE_LINUX_FS_H 1

/* Define to 1 if you have the `localtime' function. */
#define HAVE_LOCALTIME 1

/* Define to 1 if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define to 1 if you have the `mbsinit' function. */
/* #undef HAVE_MBSINIT */

/* Define to 1 if you have the `mbsrtowcs' function. */
/* #undef HAVE_MBSRTOWCS */

/* Define to 1 if you have the `memchr' function. */
#define HAVE_MEMCHR 1

/* Define to 1 if you have the `memcmp' function. */
#define HAVE_MEMCMP 1

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memrchr' function. */
#define HAVE_MEMRCHR 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <openssl/evp.h> header file. */
#define HAVE_OPENSSL_EVP_H 1

/* Define to 1 if you have the <openssl/md5.h> header file. */
#define HAVE_OPENSSL_MD5_H 1

/* Define to 1 if you have the <openssl/opensslv.h> header file. */
#define HAVE_OPENSSL_OPENSSLV_H 1

/* Define to 1 if you have the <openssl/sha.h> header file. */
#define HAVE_OPENSSL_SHA_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `sprintf' function. */
#define HAVE_SPRINTF 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strcmp' function. */
#define HAVE_STRCMP 1

/* Define to 1 if you have the `strcpy' function. */
#define HAVE_STRCPY 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `strerror_r' function. */
#define HAVE_STRERROR_R 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlen' function. */
#define HAVE_STRLEN 1

/* Define to 1 if you have the `strncmp' function. */
#define HAVE_STRNCMP 1

/* Define to 1 if you have the `strncpy' function. */
#define HAVE_STRNCPY 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the `swprintf' function. */
/* #undef HAVE_SWPRINTF */

/* Define to 1 if you have the <sys/disklabel.h> header file. */
/* #undef HAVE_SYS_DISKLABEL_H */

/* Define to 1 if you have the <sys/disk.h> header file. */
/* #undef HAVE_SYS_DISK_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/signal.h> header file. */
#define HAVE_SYS_SIGNAL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the `uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Defines if uuid_generate_random funtion is present in libuuid. */
#define HAVE_UUID_GENERATE_RANDOM 1

/* Defines if uuid_generate_time funtion is present in libuuid. */
#define HAVE_UUID_GENERATE_TIME 1

/* Define to 1 if you have the <uuid/uuid.h> header file. */
#define HAVE_UUID_UUID_H 1

/* Define to 1 if you have the <varargs.h> header file. */
/* #undef HAVE_VARARGS_H */

/* Defines if verbose output should be used */
/* #undef HAVE_VERBOSE_OUTPUT */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
/* #undef HAVE_WCHAR_H */

/* Define to 1 if you have the `wcschr' function. */
/* #undef HAVE_WCSCHR */

/* Define to 1 if you have the `wcscmp' function. */
/* #undef HAVE_WCSCMP */

/* Define to 1 if you have the `wcscpy' function. */
/* #undef HAVE_WCSCPY */

/* Define to 1 if you have the `wcsdup' function. */
/* #undef HAVE_WCSDUP */

/* Define to 1 if you have the `wcslen' function. */
/* #undef HAVE_WCSLEN */

/* Define to 1 if you have the `wcsncmp' function. */
/* #undef HAVE_WCSNCMP */

/* Define to 1 if you have the `wcsncpy' function. */
/* #undef HAVE_WCSNCPY */

/* Define to 1 if you have the `wcsrchr' function. */
/* #undef HAVE_WCSRCHR */

/* Define to 1 if you have the `wcsrtombs' function. */
/* #undef HAVE_WCSRTOMBS */

/* Define to 1 if you have the `wcstol' function. */
/* #undef HAVE_WCSTOL */

/* Define to 1 if you have the `wcstoul' function. */
/* #undef HAVE_WCSTOUL */

/* Define to 1 if you have the `wctob' function. */
/* #undef HAVE_WCTOB */

/* Defines if wide character type should be used */
/* #undef HAVE_WIDE_CHARACTER_TYPE */

/* Define to 1 if you have the `wmain' function. */
/* #undef HAVE_WMAIN */

/* Define to 1 if you have the `wmemchr' function. */
/* #undef HAVE_WMEMCHR */

/* Define to 1 if you have the `wmemcmp' function. */
/* #undef HAVE_WMEMCMP */

/* Define to 1 if you have the `wmemcpy' function. */
/* #undef HAVE_WMEMCPY */

/* Define to 1 if you have the `wmemrchr' function. */
/* #undef HAVE_WMEMRCHR */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Defines the fallback operating system string. */
#define LIBEWF_OPERATING_SYSTEM "Linux"

/* Name of package */
#define PACKAGE "libewf"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "forensics@hoffmannbv.nl"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libewf"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libewf 20070512"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libewf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "20070512"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if strerror_r returns char *. */
/* #undef STRERROR_R_CHAR_P */

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "20070512"

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `signed' if <sys/types.h> does not define. */
/* #undef ssize_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
